export const SUBSCRIPTION_PLANS = [
  {
    id: "starter",
    name: "Essentiel",
    description: "Pour les petits établissements qui veulent tester sans risque",
    monthlyPrice: 49,
    amountCents: 4900,
    callRate: "0,19€ / minute d'appel",
    /** Tarif en centimes d'euro par minute d'appel IA */
    callRateCentsPerMinute: 19,
    /** Nombre maximum de restaurants dans l'organisation (null = illimité) */
    maxRestaurants: 1,
    popular: false,
    popularLabel: "Populaire",
    included: [
      "1 numéro de téléphone dédié",
      "4 appels simultanés max",
      "IA vocale 24h/24, 7j/7",
      "Dashboard tablette",
      "Gestion des commandes en temps réel",
      "Menu illimité",
      "Mise à jour instantanée",
      "Support email",
    ],
    excluded: [],
  },
  {
    id: "essential",
    name: "Pro",
    description: "Pour les établissements actifs qui veulent une solution complète",
    monthlyPrice: 99,
    amountCents: 9900,
    callRate: "0,17€ / minute d'appel",
    callRateCentsPerMinute: 17,
    maxRestaurants: 1,
    popular: true,
    popularLabel: "Le plus choisi",
    included: [
      "1 numéro de téléphone dédié",
      "2 appels simultanés supplémentaires max",
      "IA vocale 24h/24, 7j/7",
      "Dashboard tablette",
      "Gestion des commandes en temps réel",
      "Menu illimité",
      "Mise à jour instantanée",
      "Support email",
      "Connexion logiciel de caisse",
      "Sépare commandes & renseignements",
      "Analytics & historique des appels",
      "Rapports hebdomadaires par email",
      "Support email prioritaire",
      "Réponse sous 4h en semaine",
    ],
    excluded: [],
  },
  {
    id: "infinity",
    name: "Business",
    description: "Pour les établissements à fort volume ou les chaînes multi-sites",
    monthlyPrice: 199,
    amountCents: 19900,
    callRate: "0,15€ / minute d'appel",
    callRateCentsPerMinute: 15,
    /** null = illimité */
    maxRestaurants: null,
    popular: false,
    popularLabel: "Populaire",
    included: [
      "1 numéro de téléphone dédié par restaurant",
      "10 appels simultanés max",
      "IA vocale 24h/24, 7j/7",
      "Dashboard tablette",
      "Gestion des commandes en temps réel",
      "Menu illimité",
      "Mise à jour instantanée",
      "Support email",
      "Connexion logiciel de caisse",
      "Sépare commandes & renseignements",
      "Analytics & historique des appels",
      "Rapports hebdomadaires par email",
      "Support prioritaire",
      "Réponse sous 4h en semaine",
      "Transfert vers humain",
      "Bascule vers un employé si besoin",
      "Personnalisation avancée de l'IA",
      "Ton, script, promotions...",
      "Multi-sites",
      "Gérez plusieurs adresses depuis un dashboard",
      "Support dédié",
      "Interlocuteur fixe, réponse sous 1h",
    ],
    excluded: [],
  },
] as const;

export type PlanId = (typeof SUBSCRIPTION_PLANS)[number]["id"];
